# Generated by Django 4.2.10 on 2024-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name="Vendor's name")),
                ('contact_details', models.TextField(verbose_name=' Contact information of the vendor')),
                ('address', models.TextField(verbose_name='Physical address of the vendor')),
                ('vendor_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='A unique identiﬁer for the vendor')),
                ('on_time_delivery_rate', models.FloatField(default=0.0, verbose_name='Percentage of on-time deliveries')),
                ('quality_rating_avg', models.FloatField(default=0.0, verbose_name='Average rating of quality')),
                ('average_response_time', models.FloatField(default=0.0, verbose_name='Average time taken to acknowledge purchase orders')),
                ('fulfillment_rate', models.FloatField(default=0.0, verbose_name=' Percentage of purchase orders fulﬁlled successfully')),
            ],
        ),
    ]
